filter:
  trigger_prefix: ''
gewechat:
  app_id: wx_LdauLALCj7rrWlHhdwAZm
  base_url: http://192.168.31.189:2531/v2/api
  callback_url: http://192.168.31.176:9001/v2/api/callback/collect
  download_url: http://192.168.31.189:2532/download
  token: 881f5e8b13a84509a284c17e429d9ee1
